theme: jekyll-theme-minimal
title: API Client PIX (BACEN) .NET
description: A .NET implementation of PIX contracts available at https://github.com/bacen/pix-api/
logo: https://raw.githubusercontent.com/guibranco/PIX-BACEN/master/logo.png
show_downloads: true
